added new checks

diff --git a/.github/workflows/deploy_branch_release.yml b/.github/workflows/deploy_branch_release.yml
--- a/.github/workflows/deploy_branch_release.yml
+++ b/.github/workflows/deploy_branch_release.yml
@@ -12,7 +12,6 @@ on:
         - minor
         - patch
         default: 'patch'
-
 jobs:
   create_release_branch:
     runs-on: ubuntu-latest
@@ -24,6 +23,21 @@ jobs:
         with:
           fetch-depth: 0
           token: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: Check base branch
+        run: |
+          current_branch=$(git rev-parse --abbrev-ref HEAD)
+          if [ "$current_branch" != "develop" ]; then
+            echo "Error: Must be on 'develop' branch. Current branch: $current_branch"
+            exit 1
+          fi
+
+      - name: Check for uncommitted changes
+        run: |
+          if ! git diff-index --quiet HEAD --; then
+            echo "Error: There are uncommitted changes in the working directory"
+            exit 1
+          fi
 
       - name: Get current version
         id: get_version
