Update and rename create-release-branch-from-develop.yml to develop-to-release.yml

diff --git a/.github/workflows/develop-to-release.yml b/.github/workflows/develop-to-release.yml
--- a/.github/workflows/develop-to-release.yml
+++ b/.github/workflows/develop-to-release.yml
@@ -1,4 +1,4 @@
-name: create-release-branch-from-develop
+name: develop-to-release
 
 on:
   workflow_dispatch:
@@ -104,4 +104,6 @@ jobs:
         if: steps.check_branch.outputs.branch_exists == 'true'
         run: |
           release_type=${{ github.event.inputs.release_type }}
-          new_version="${{ steps.calc_version.outputs.new_version
+          new_version="${{ steps.calc_version.outputs.new_version }}"
+          echo "Error: Branch release-${release_type}-v${new_version} already exists"
+          exit 1
